### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zhuweideng** [aidevjoe/V2EX#10]
Build/Intermediates.noindex/V2EX.build/Debug-iphonesimulator/V2EX.build/Script-D81F752D21A6B55B00EC0427.sh: line 2: embed-alternate-icons: command not found
Command PhaseScriptExecution failed with a nonzero exit code

Xcode 10.1
Swift 4.2

**Comment by tzqiang** [comment]
我也遇到了，主要是 alternate-icons 的问题。
访问 https://github.com/alexaubry/alternate-icons 查看。
安装之后重新编译就可以了。
`git clone https://github.com/alexaubry/alternate-icons.git
cd alternate-icons
make
make install`
