### ISSUE TITLE
下载后运行问题

### ISSUE THREAD

**Issue by huyabin** [aidevjoe/V2EX#13]
git clone下来之后 pod install之后报这个错。百度了一下也没解决，有什么方法可以解决吗？

```

/Library/Developer/Xcode/DerivedData/V2EX-djwkwlnkbtqokyaoiwhsknqsoesf/Build/Intermediates.noindex/V2EX.build/Debug-iphonesimulator/V2EX.build/Script-D81F752D21A6B55B00EC0427.sh: line 2: embed-alternate-icons: command not found
Command PhaseScriptExecution failed with a nonzero exit code

```

**Comment by ZDerain** [comment]
我也碰见了问题, 根据错误提示; 做了如下修改, 即可运行;

Targets -> buildPhases ->alternate-icons -> RunScript only ...   选中即可.

**Comment by ZDerain** [comment]
> git clone下来之后 pod install之后报这个错。百度了一下也没解决，有什么方法可以解决吗？
> 
> ```
> 
> /Library/Developer/Xcode/DerivedData/V2EX-djwkwlnkbtqokyaoiwhsknqsoesf/Build/Intermediates.noindex/V2EX.build/Debug-iphonesimulator/V2EX.build/Script-D81F752D21A6B55B00EC0427.sh: line 2: embed-alternate-icons: command not found
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
我也碰见了问题, 根据错误提示; 做了如下修改, 即可运行;

Targets -> buildPhases ->alternate-icons -> RunScript only ... 选中即可.

**Comment by huyabin** [comment]
> > git clone下来之后 pod install之后报这个错。百度了一下也没解决，有什么方法可以解决吗？
> > ```
> > 
> > /Library/Developer/Xcode/DerivedData/V2EX-djwkwlnkbtqokyaoiwhsknqsoesf/Build/Intermediates.noindex/V2EX.build/Debug-iphonesimulator/V2EX.build/Script-D81F752D21A6B55B00EC0427.sh: line 2: embed-alternate-icons: command not found
> > Command PhaseScriptExecution failed with a nonzero exit code
> > ```
> 
> 我也碰见了问题, 根据错误提示; 做了如下修改, 即可运行;
> 
> Targets -> buildPhases ->alternate-icons -> RunScript only ... 选中即可.
 感谢，运行起来。
