### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ekgg** [aidevjoe/V2EX#9]
there are some complie error:
./V2EX/Views/Cells/BaseTableViewCell.swift:31:14: Initializer does not override a designated initializer from its superclass

./V2EX/Views/Cells/BaseTableViewCell.swift:31:42: 'CellStyle' is not a member type of 'UITableViewCell'

./V2EX/Views/BrowserActivity/BrowserActivity.swift:45:29: 'ActivityType' is not a member type of 'UIActivity'

test compile with:
Xcode 9.1,Swift4.0, 
Xcode 9.3.1, Swift4.1

**Comment by aidevjoe** [comment]
Please Compile with Xcode 10
